images: use external kickstart file for rhel4edge
Fixes #5774

diff --git a/images/scripts/virt-install-rhel4edge b/images/scripts/virt-install-rhel4edge
--- a/images/scripts/virt-install-rhel4edge
+++ b/images/scripts/virt-install-rhel4edge
@@ -32,8 +32,18 @@ fi
 out=$1
 arch=$2
 url=$3
+VERSION="9-2"
+VIRT_WAIT="10" # wait 10 minutes to finish installation
+virt_log_file="$(basename $url).log"
 
 base=$(dirname $0)
+
+# HACK: Extract fleet.ks file and fix the kickstart for rhel4edge.
+# 'rootpw' parameter has to be defined for non-interactive installation
+# https://issues.redhat.com/browse/THEEDGE-3825
+fleet_ks_file="$(basename $url).ks"
+isoinfo  -i $url -x "/FLEET.KS;1" > "$fleet_ks_file"
+sed -i "/network --boot/a rootpw --lock" "$fleet_ks_file"
 
 qemu-img create -f qcow2 "$out" 12G
 
@@ -49,43 +59,33 @@ cleanup_builder_vm () {
   fi
 }
 
-# Using virt-install is fundamentally an interactive process.  We
-# expect the installation to finish unattended, but it might drop into
-# an emergency shell upon unexpected errors, for example.  Thus, we
-# run it under 'expect' and catch a few known scenarios that require
-# special handling.
-#
-# (Also, virt-install works best when it has a tty.)
-
-supervised_virt_install () {
-expect -- - virt-install "$@" <<'EOF'
-eval spawn $argv
-set timeout -1
-expect {
-  "emergency mode" { send_user "\n\n\n\nABORT - emergency shell\n"
-                     exit 1
-                   }
-  "Please make your choice" { send_user "\n\n\n\nABORT - Anaconda stopped\n"
-                              exit 1
-                            }
-  "Please make a selection" { send_user "\n\n\n\nABORT - Anaconda stopped\n"
-                              exit 1
-                            }
-}
-EOF
-}
-
 cleanup_builder_vm
 
-
-supervised_virt_install $connect \
+virt-install $connect \
                         --name=$name \
-                        --extra-args="inst.stage2=hd:LABEL=RHEL-9-2-0-BaseOS-x86_64 inst.ks=hd:LABEL=RHEL-9-2-0-BaseOS-x86_64:/fleet.ks console=ttyS0,115200" \
+                        --extra-args="inst.stage2=hd:LABEL=RHEL-${VERSION}-0-BaseOS-x86_64 inst.ks=file:/$fleet_ks_file console=ttyS0,115200" \
                         --disk "path=$out,format=qcow2" \
                         --ram 4096 \
                         --vcpus=1 \
                         --location="$url" \
                         --nographics \
-                        --noreboot
+                        --initrd-inject="$(realpath $fleet_ks_file)" \
+                        --noreboot \
+                        --serial=file,path="$(realpath $virt_log_file)" \
+                        --noautoconsole \
+                        --wait "$VIRT_WAIT" || true
+machine_status="$(virsh $connect dominfo $name | grep State: | sed 's/State:\s*//')"
 
 cleanup_builder_vm
+
+
+rm "$fleet_ks_file"
+if echo "$machine_status" | grep "shut off"; then
+    rm "$virt_log_file"
+    echo "INSTALLATION PASSED"
+else
+    cat $virt_log_file | sed 's/[[:cntrl:]]//g'
+    rm "$virt_log_file"
+    echo "INSTALLATION FAILED"
+    exit 1
+fi
